spring:
  cloud:
    gcp:
      project-id: st-misc-demo
      pubsub:
        subscriber:
          max-ack-extension-period: 10
          flow-control:
            max-outstanding-element-count: 4
          executor-threads: 4
